// Inline data — no fetch needed.
window.FLIGHTS = [
  {"date":"2020-07-03","flight":"","from":"OSR","to":"BOJ","duration":"01:41:00","airline":"","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2020-07-10","flight":"","from":"BOJ","to":"OSR","duration":"01:41:00","airline":"","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2021-07-27","flight":"","from":"BTS","to":"AHO","duration":"01:43:00","airline":"","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2021-07-31","flight":"","from":"AHO","to":"BTS","duration":"01:43:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2022-03-31","flight":"","from":"VIE","to":"NCE","duration":"01:26:00","airline":"Wizz Air","aircraft":"","reg":"","seat":"","seatType":2,"class":0,"reason":1,"note":""},
  {"date":"2022-04-03","flight":"","from":"NCE","to":"VIE","duration":"01:26:00","airline":"Wizz Air","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2022-04-26","flight":"","from":"VIE","to":"PMI","duration":"02:13:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2022-04-28","flight":"","from":"PMI","to":"VIE","duration":"02:13:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2022-07-12","flight":"","from":"PRG","to":"AMS","duration":"01:12:00","airline":"Easyjet","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2022-07-15","flight":"","from":"CRL","to":"VIE","duration":"01:29:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2022-08-20","flight":"","from":"VIE","to":"JSI","duration":"01:47:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2022-08-22","flight":"","from":"JSI","to":"VIE","duration":"01:47:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2022-10-29","flight":"","from":"VIE","to":"PMI","duration":"02:13:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2022-10-30","flight":"","from":"PMI","to":"SVQ","duration":"01:18:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2022-11-06","flight":"","from":"SVQ","to":"PMI","duration":"01:18:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":2,"class":0,"reason":1,"note":""},
  {"date":"2022-11-06","flight":"","from":"PMI","to":"VIE","duration":"02:13:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2022-11-08","flight":"","from":"VIE","to":"LPL","duration":"02:14:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2022-11-12","flight":"","from":"MAN","to":"BTS","duration":"02:15:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":3,"class":0,"reason":1,"note":""},
  {"date":"2023-01-20","flight":"","from":"BRQ","to":"STN","duration":"01:52:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-01-21","flight":"","from":"STN","to":"BRQ","duration":"01:52:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-02-08","flight":"","from":"VIE","to":"BGY","duration":"01:02:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-02-11","flight":"","from":"BGY","to":"BTS","duration":"01:06:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-03-29","flight":"","from":"VIE","to":"IBZ","duration":"02:24:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2023-03-29","flight":"","from":"IBZ","to":"LIS","duration":"01:28:00","airline":"Easyjet","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2023-04-08","flight":"","from":"LIS","to":"STN","duration":"02:27:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":3,"class":0,"reason":1,"note":""},
  {"date":"2023-04-09","flight":"","from":"STN","to":"PRG","duration":"01:36:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":3,"class":0,"reason":1,"note":""},
  {"date":"2023-06-04","flight":"","from":"VIE","to":"PUY","duration":"00:48:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-06-05","flight":"","from":"PUY","to":"VIE","duration":"00:48:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-07-25","flight":"","from":"BTS","to":"ZAG","duration":"00:37:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-07-27","flight":"","from":"ZAG","to":"BTS","duration":"00:37:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-08-09","flight":"","from":"VIE","to":"FCO","duration":"01:18:00","airline":"Wizz Air","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-08-10","flight":"","from":"FCO","to":"VIE","duration":"01:18:00","airline":"Wizz Air","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-08-16","flight":"","from":"VIE","to":"AGP","duration":"03:08:00","airline":"Wizz Air","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2023-08-21","flight":"","from":"SVQ","to":"IBZ","duration":"01:08:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-08-22","flight":"","from":"IBZ","to":"VIE","duration":"02:24:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-09-08","flight":"","from":"PRG","to":"BVA","duration":"01:25:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-09-08","flight":"","from":"BVA","to":"OPO","duration":"01:55:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":0,"reason":1,"note":""},
  {"date":"2023-09-19","flight":"","from":"OPO","to":"VIE","duration":"03:07:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":2,"class":0,"reason":1,"note":""},
  {"date":"2023-10-20","flight":"","from":"BTS","to":"CFU","duration":"01:34:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":1,"class":0,"reason":1,"note":""},
  {"date":"2023-10-22","flight":"","from":"CFU","to":"BTS","duration":"01:34:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":3,"class":0,"reason":1,"note":""},
  {"date":"2024-01-20","flight":"","from":"VIE","to":"AGA","duration":"04:15:00","airline":"Ryanair","aircraft":"","reg":"","seat":"01A","seatType":1,"class":1,"reason":1,"note":""},
  {"date":"2024-01-23","flight":"","from":"AGA","to":"VIE","duration":"04:15:00","airline":"Ryanair","aircraft":"","reg":"","seat":"03A","seatType":1,"class":1,"reason":1,"note":""},
  {"date":"2024-02-06","flight":"","from":"VIE","to":"OHD","duration":"01:22:00","airline":"Wizz Air","aircraft":"","reg":"","seat":"33C","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2024-02-08","flight":"","from":"OHD","to":"VIE","duration":"01:22:00","airline":"Wizz Air","aircraft":"","reg":"","seat":"18C","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2024-04-05","flight":"","from":"BTS","to":"KUN","duration":"01:27:00","airline":"Ryanair","aircraft":"","reg":"","seat":"16B","seatType":2,"class":1,"reason":1,"note":""},
  {"date":"2024-04-06","flight":"","from":"KUN","to":"BTS","duration":"01:27:00","airline":"Ryanair","aircraft":"","reg":"","seat":"5B","seatType":2,"class":1,"reason":1,"note":""},
  {"date":"2024-04-28","flight":"","from":"VIE","to":"CPH","duration":"01:26:00","airline":"Ryanair","aircraft":"","reg":"","seat":"08C","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2024-04-30","flight":"","from":"CPH","to":"PRG","duration":"01:05:00","airline":"Ryanair","aircraft":"","reg":"","seat":"17C","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2024-06-16","flight":"","from":"VIE","to":"LAX","duration":"13:33:00","airline":"Austrian Airlines","aircraft":"","reg":"","seat":"40H","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2024-06-17","flight":"","from":"LAX","to":"KOA","duration":"05:41:00","airline":"United Airlines","aircraft":"","reg":"","seat":"18B","seatType":2,"class":1,"reason":1,"note":""},
  {"date":"2024-09-05","flight":"DL485","from":"KOA","to":"SEA","duration":"05:54:00","airline":"Delta Air Lines","aircraft":"Airbus A321neo","reg":"N538DN","seat":"32A","seatType":1,"class":0,"reason":4,"note":"Jakubkooo"},
  {"date":"2024-09-08","flight":"UA656","from":"SEA","to":"SFO","duration":"02:14:00","airline":"United Airlines","aircraft":"Airbus A319","reg":"N851UA","seat":"24D","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2024-09-10","flight":"F94594","from":"SFO","to":"LAX","duration":"01:28:00","airline":"Frontier Airlines","aircraft":"Airbus A320neo","reg":"N310FR","seat":"29F","seatType":1,"class":1,"reason":1,"note":""},
  {"date":"2024-09-13","flight":"NK473","from":"LAX","to":"LAS","duration":"01:19:00","airline":"Spirit Airlines","aircraft":"Airbus A320","reg":"N628NK","seat":"14E","seatType":2,"class":1,"reason":1,"note":""},
  {"date":"2024-09-14","flight":"NK1495","from":"LAS","to":"LAX","duration":"01:18:00","airline":"Spirit Airlines","aircraft":"Airbus A320","reg":"N691NK","seat":"23A","seatType":1,"class":1,"reason":1,"note":""},
  {"date":"2024-09-15","flight":"OS82","from":"LAX","to":"VIE","duration":"11:25:00","airline":"Austrian Airlines","aircraft":"Boeing 777-200","reg":"OE-LPB","seat":"41H","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2024-10-26","flight":"FR8227","from":"BTS","to":"AHO","duration":"01:55:00","airline":"Ryanair","aircraft":"Boeing 737-800","reg":"SP-RKD","seat":"4A","seatType":1,"class":1,"reason":1,"note":""},
  {"date":"2024-10-26","flight":"FR8978","from":"AHO","to":"BCN","duration":"01:20:00","airline":"Ryanair","aircraft":"Boeing 737-800","reg":"","seat":"8F","seatType":1,"class":1,"reason":1,"note":"Odlet o 18 hodin později, ubytko zdarma."},
  {"date":"2024-10-29","flight":"FR846","from":"BCN","to":"BGY","duration":"01:45:00","airline":"Ryanair","aircraft":"Boeing 737 MAX 8","reg":"9H-VVM","seat":"29E","seatType":2,"class":1,"reason":1,"note":""},
  {"date":"2024-10-29","flight":"FR4642","from":"BGY","to":"BTS","duration":"01:24:00","airline":"Ryanair","aircraft":"Boeing 737-800","reg":"SP-RKL","seat":"4F","seatType":0,"class":1,"reason":1,"note":""},
  {"date":"2024-11-09","flight":"FR735","from":"VIE","to":"TLL","duration":"02:25:00","airline":"Ryanair","aircraft":"Airbus A320","reg":"9H-LOQ","seat":"1B","seatType":0,"class":1,"reason":0,"note":"Dominik"},
  {"date":"2024-11-11","flight":"FR736","from":"TLL","to":"VIE","duration":"02:25:00","airline":"Ryanair","aircraft":"Airbus A320","reg":"9H-LOQ","seat":"1A","seatType":1,"class":0,"reason":0,"note":""},
  {"date":"2025-02-06","flight":"FR6890","from":"VIE","to":"TIA","duration":"01:40:00","airline":"Ryanair","aircraft":"","reg":"","seat":"","seatType":0,"class":1,"reason":1,"note":""},
  {"date":"2025-02-09","flight":"FR6889","from":"TIA","to":"VIE","duration":"01:40:00","airline":"Ryanair","aircraft":"Boeing 737 MAX 8","reg":"","seat":"","seatType":0,"class":1,"reason":1,"note":""},
  {"date":"2025-07-26","flight":"TR711","from":"VIE","to":"SIN","duration":"11:25:00","airline":"Scoot","aircraft":"Boeing 787-8","reg":"9V-OFL","seat":"40C","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2025-07-27","flight":"TR288","from":"SIN","to":"DPS","duration":"02:45:00","airline":"Scoot","aircraft":"Boeing 787-8","reg":"9V-OFL","seat":"27B","seatType":2,"class":1,"reason":1,"note":""},
  {"date":"2025-08-08","flight":"TR281","from":"DPS","to":"SIN","duration":"02:40:00","airline":"Scoot","aircraft":"Boeing 787-8","reg":"9V-OFE","seat":"40C","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2025-08-09","flight":"TR710","from":"SIN","to":"VIE","duration":"12:05:00","airline":"Scoot","aircraft":"Boeing 787-8","reg":"9V-OFK","seat":"40C","seatType":3,"class":0,"reason":1,"note":""},
  {"date":"2025-11-16","flight":"PC412","from":"BTS","to":"SAW","duration":"02:10:00","airline":"Pegasus Airlines","aircraft":"Airbus A321neo","reg":"TC-RFO","seat":"22F","seatType":1,"class":1,"reason":1,"note":""},
  {"date":"2025-11-18","flight":"PC905","from":"SAW","to":"VIE","duration":"02:20:00","airline":"Pegasus Airlines","aircraft":"Airbus A321neo","reg":"TC-RBT","seat":"22B","seatType":2,"class":1,"reason":1,"note":""},
  {"date":"2026-01-17","flight":"W42861","from":"VIE","to":"AGP","duration":"03:35:00","airline":"Aero Services Executive","aircraft":"Airbus A321neo","reg":"9H-WAG","seat":"15C","seatType":3,"class":1,"reason":1,"note":"Rychlovýlet"},
  {"date":"2026-01-18","flight":"W67026","from":"AGP","to":"BTS","duration":"03:25:00","airline":"Wizz Air","aircraft":"Airbus A321neo","reg":"HA-LGQ","seat":"19B","seatType":2,"class":1,"reason":1,"note":""},
  {"date":"2026-02-17","flight":"W42831","from":"VIE","to":"TFS","duration":"04:35:00","airline":"Aero Services Executive","aircraft":"Airbus A321neo","reg":"9H-WDE","seat":"40D","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2026-02-21","flight":"IB1554","from":"TFS","to":"MAD","duration":"03:50:00","airline":"Iberia","aircraft":"Airbus A320","reg":"EC-KOH","seat":"17C","seatType":3,"class":1,"reason":1,"note":""},
  {"date":"2026-02-21","flight":"FR690","from":"MAD","to":"VIE","duration":"03:05:00","airline":"Ryanair","aircraft":"Boeing 737 MAX 8","reg":"EI-ILD","seat":"4B","seatType":2,"class":1,"reason":1,"note":""}
]
;
window.AIRPORTS = {
  "AGA":{"city":"Agadir","name":"Almassira","iata":"AGA","icao":"GMAD","lat":30.3811,"lon":-9.5461,"country":"Maroko","iso":"MA"},
  "AGP":{"city":"Málaga","name":"Costa Del Sol","iata":"AGP","icao":"LEMG","lat":36.6749,"lon":-4.4991,"country":"Španělsko","iso":"ES"},
  "AHO":{"city":"Alghero","name":"Fertilia","iata":"AHO","icao":"LIEA","lat":40.6321,"lon":8.2908,"country":"Itálie","iso":"IT"},
  "AMS":{"city":"Amsterdam","name":"Schiphol","iata":"AMS","icao":"EHAM","lat":52.3086,"lon":4.7639,"country":"Nizozemsko","iso":"NL"},
  "BCN":{"city":"Barcelona","name":"El Prat","iata":"BCN","icao":"LEBL","lat":41.2974,"lon":2.0833,"country":"Španělsko","iso":"ES"},
  "BGY":{"city":"Bergamo","name":"Orio Al Serio","iata":"BGY","icao":"LIME","lat":45.6739,"lon":9.7042,"country":"Itálie","iso":"IT"},
  "BOJ":{"city":"Burgas","name":"Burgas","iata":"BOJ","icao":"LBBG","lat":42.5696,"lon":27.5152,"country":"Bulharsko","iso":"BG"},
  "BRQ":{"city":"Brno","name":"Brno-Tuřany","iata":"BRQ","icao":"LKTB","lat":49.1513,"lon":16.6944,"country":"Česko","iso":"CZ"},
  "BTS":{"city":"Bratislava","name":"M. R. Štefánika","iata":"BTS","icao":"LZIB","lat":48.1702,"lon":17.2127,"country":"Slovensko","iso":"SK"},
  "BVA":{"city":"Beauvais","name":"Beauvais Tillé","iata":"BVA","icao":"LFOB","lat":49.4544,"lon":2.1128,"country":"Francie","iso":"FR"},
  "CFU":{"city":"Kerkyra","name":"Ioannis Kapodistrias","iata":"CFU","icao":"LGKR","lat":39.6019,"lon":19.9117,"country":"Řecko","iso":"GR"},
  "CPH":{"city":"Kodaň","name":"Kastrup","iata":"CPH","icao":"EKCH","lat":55.618,"lon":12.656,"country":"Dánsko","iso":"DK"},
  "CRL":{"city":"Charleroi","name":"Brussels South","iata":"CRL","icao":"EBCI","lat":50.4592,"lon":4.4538,"country":"Belgie","iso":"BE"},
  "DPS":{"city":"Denpasar","name":"Ngurah Rai","iata":"DPS","icao":"WADD","lat":-8.7482,"lon":115.1672,"country":"Indonésie","iso":"ID"},
  "FCO":{"city":"Řím","name":"Fiumicino","iata":"FCO","icao":"LIRF","lat":41.8003,"lon":12.2389,"country":"Itálie","iso":"IT"},
  "IBZ":{"city":"Ibiza","name":"Ibiza","iata":"IBZ","icao":"LEIB","lat":38.8729,"lon":1.3731,"country":"Španělsko","iso":"ES"},
  "JSI":{"city":"Skiathos","name":"Skiathos","iata":"JSI","icao":"LGSK","lat":39.1771,"lon":23.5037,"country":"Řecko","iso":"GR"},
  "KOA":{"city":"Kailua-Kona","name":"Kailua-Kona","iata":"KOA","icao":"PHKO","lat":19.7388,"lon":-156.0456,"country":"USA","iso":"US"},
  "KUN":{"city":"Kaunas","name":"Kaunas","iata":"KUN","icao":"EYKA","lat":54.9639,"lon":24.0848,"country":"Litva","iso":"LT"},
  "LAS":{"city":"Las Vegas","name":"McCarran","iata":"LAS","icao":"KLAS","lat":36.084,"lon":-115.1537,"country":"USA","iso":"US"},
  "LAX":{"city":"Los Angeles","name":"LAX","iata":"LAX","icao":"KLAX","lat":33.9416,"lon":-118.4085,"country":"USA","iso":"US"},
  "LIS":{"city":"Lisabon","name":"Portela","iata":"LIS","icao":"LPPT","lat":38.7742,"lon":-9.1342,"country":"Portugalsko","iso":"PT"},
  "LPL":{"city":"Liverpool","name":"John Lennon","iata":"LPL","icao":"EGGP","lat":53.3336,"lon":-2.8497,"country":"Velká Británie","iso":"GB"},
  "MAD":{"city":"Madrid","name":"Barajas","iata":"MAD","icao":"LEMD","lat":40.4936,"lon":-3.5668,"country":"Španělsko","iso":"ES"},
  "MAN":{"city":"Manchester","name":"Manchester","iata":"MAN","icao":"EGCC","lat":53.3537,"lon":-2.275,"country":"Velká Británie","iso":"GB"},
  "NCE":{"city":"Nice","name":"Côte d'Azur","iata":"NCE","icao":"LFMN","lat":43.6584,"lon":7.2159,"country":"Francie","iso":"FR"},
  "OHD":{"city":"Ohrid","name":"Ohrid","iata":"OHD","icao":"LWOH","lat":41.1801,"lon":20.7423,"country":"Sev. Makedonie","iso":"MK"},
  "OPO":{"city":"Porto","name":"Francisco Sá Carneiro","iata":"OPO","icao":"LPPR","lat":41.2481,"lon":-8.6814,"country":"Portugalsko","iso":"PT"},
  "OSR":{"city":"Ostrava","name":"Mošnov","iata":"OSR","icao":"LKMT","lat":49.6963,"lon":18.1111,"country":"Česko","iso":"CZ"},
  "PMI":{"city":"Palma de Mallorca","name":"Son Sant Joan","iata":"PMI","icao":"LEPA","lat":39.5517,"lon":2.7388,"country":"Španělsko","iso":"ES"},
  "PRG":{"city":"Praha","name":"Václav Havel","iata":"PRG","icao":"LKPR","lat":50.1008,"lon":14.26,"country":"Česko","iso":"CZ"},
  "PUY":{"city":"Pula","name":"Pula","iata":"PUY","icao":"LDPL","lat":44.8935,"lon":13.9222,"country":"Chorvatsko","iso":"HR"},
  "SAW":{"city":"Istanbul","name":"Sabiha Gökçen","iata":"SAW","icao":"LTFJ","lat":40.8986,"lon":29.3092,"country":"Turecko","iso":"TR"},
  "SEA":{"city":"Seattle","name":"Seattle-Tacoma","iata":"SEA","icao":"KSEA","lat":47.4502,"lon":-122.3088,"country":"USA","iso":"US"},
  "SFO":{"city":"San Francisco","name":"SFO","iata":"SFO","icao":"KSFO","lat":37.6213,"lon":-122.379,"country":"USA","iso":"US"},
  "SIN":{"city":"Singapur","name":"Changi","iata":"SIN","icao":"WSSS","lat":1.3644,"lon":103.9915,"country":"Singapur","iso":"SG"},
  "STN":{"city":"Londýn","name":"Stansted","iata":"STN","icao":"EGSS","lat":51.886,"lon":0.2389,"country":"Velká Británie","iso":"GB"},
  "SVQ":{"city":"Sevilla","name":"San Pablo","iata":"SVQ","icao":"LEZL","lat":37.418,"lon":-5.8931,"country":"Španělsko","iso":"ES"},
  "TFS":{"city":"Tenerife","name":"Reina Sofía","iata":"TFS","icao":"GCTS","lat":28.0445,"lon":-16.5725,"country":"Španělsko","iso":"ES"},
  "TIA":{"city":"Tirana","name":"Rinas","iata":"TIA","icao":"LATI","lat":41.4147,"lon":19.7206,"country":"Albánie","iso":"AL"},
  "TLL":{"city":"Tallinn","name":"Ülemiste","iata":"TLL","icao":"EETN","lat":59.4133,"lon":24.8328,"country":"Estonsko","iso":"EE"},
  "VIE":{"city":"Vídeň","name":"Schwechat","iata":"VIE","icao":"LOWW","lat":48.1103,"lon":16.5697,"country":"Rakousko","iso":"AT"},
  "ZAG":{"city":"Záhřeb","name":"Franjo Tuđman","iata":"ZAG","icao":"LDZA","lat":45.7429,"lon":16.0688,"country":"Chorvatsko","iso":"HR"}
}
;
window.SEAT_TYPES = ['okno','ulička','mezi','neznámé'];
window.CLASSES = ['economy','economy','prem. eco','business','first'];
window.BUCKET = [
  { place: 'Japonsko — Tokio & Kjóto', why: 'Něco úplně jiného. Nejdelší přelet dosud.', tag: 'Asie' },
  { place: 'Island', why: 'Polární záře, ledovce, drsná estetika.', tag: 'Severský' },
  { place: 'Nový Zéland', why: 'Nejvzdálenější možný bod. Fjordland.', tag: 'Oceánie' },
  { place: 'Namibie — Sossusvlei', why: 'Červené duny na Skeleton Coast.', tag: 'Afrika' },
  { place: 'Peru — Machu Picchu', why: 'Andy, Inca Trail, výška.', tag: 'J. Amerika' },
  { place: 'Jordánsko — Petra & Wadi Rum', why: 'Poušť a architektura v jednom.', tag: 'Blízký Východ' },
  { place: 'Patagonie', why: 'Torres del Paine, konec světa.', tag: 'J. Amerika' },
  { place: 'Faerské ostrovy', why: 'Ticho, zeleň, útesy.', tag: 'Evropa' },
  { place: 'Uzbekistán — Samarkand', why: 'Hedvábná stezka naživo.', tag: 'Stř. Asie' },
  { place: 'Nepál — Annapurna', why: 'Vysokohorské treky.', tag: 'Asie' }
];
if(window.__dataReady) window.__dataReady();
else window.__dataWaiting = true;
